### ISSUE TITLE
Will this work on Mixer.com, perhaps? 

### ISSUE THREAD

**Issue by ShookieOfficial** [GlitchCog/ChatGameFontificator#16]
Is there a way to get this awesome piece of chat to work on Mixer.com as well, or? Have you tried it yet, maybe?

**Comment by GlitchCog** [comment]
I'm not familiar with Mixer.com at all, but it looks like they don't use IRC protocol for their chat, so sorry, but the Fontificator won't work with it. You'd need to strip out all the Twitch-specific stuff all throughout the program, and swap out the ChatViewerBot class with one that interfaces with Mixer's chat.
