### ISSUE TITLE
Google wrongly report Download as 'harmful'

### ISSUE THREAD

**Issue by CHEF-KOCH** [GlitchCog/ChatGameFontificator#4]
Google with enabled malware filter report it as harmful, of course it's false positive.

**Comment by CHEF-KOCH** [comment]
Sadly there exist no page to report any false positive [but I contacted manually Google over this page](https://www.google.com/safebrowsing/report_badware/) to maybe an an exclusion for your product.

**Comment by GlitchCog** [comment]
Maybe Google thinks it's malware because they consider the MANIFEST file mismatch suspicious. That's all I can think of. It's really on Google if they want to block this project. They're an impenetrable fortress of automation, so I would be really surprised if there were some human actually checking if they're accidentally hurting anyone.

**Comment by CHEF-KOCH** [comment]
I found an support forum maybe I can ask them over there to review your project. I think it's because Java are general under suspicion because it's a single .jar file. I think this is the best we could do.

**Comment by GlitchCog** [comment]
What specifically was the Google warning. Was it like a malware alert, or was it just a generic, "this is an executable file, don't run it unless you trust the source" type warning?

**Comment by CHEF-KOCH** [comment]
No malware warning, also not the red overlay. Just the warning if I want to 'keep the file' or not. As mentioned maybe it would help to pack it as .zip.

**Comment by CHEF-KOCH** [comment]
I got an email today that your project is been reviewed ~ 2-4 days.

**Comment by GlitchCog** [comment]
Any word back from the judges on high at Google regarding the Fontificator's fate?

**Comment by CHEF-KOCH** [comment]
![download](https://cloud.githubusercontent.com/assets/727123/15891676/faeebd00-2d75-11e6-971f-c6d477307b69.jpg)

**Comment by CHEF-KOCH** [comment]
okay I got reply today, the file and project is not on any 'blacklist'. This dialog coming from the Browser itself because the file extension. Sadly I not found any about:flag or something to suppress this, the only thing you can do is to mentioned this and explain that this is an harmless file. 

I close here because it seems to be an 'wontfix'.

**Comment by GlitchCog** [comment]
Yeah, I figured that might be what was going on. It's just a rando-executable, so the browser freaks out. Sort of a "if you trust the source, use at your own risk" sort of warning. Thanks for checking it out though!
