### ISSUE TITLE
BetterTTV Emote support 

### ISSUE THREAD

**Issue by CHEF-KOCH** [GlitchCog/ChatGameFontificator#6]
We already talked about that BetterTTV API is not open source or there maybe exist no public stuff directly from them. But I somehow not want to give up on it because I like the emoji.

So I searched a little bit and it seems that chatty supports FrankerZ and BetterTTV and so I think it's possible.

I found here how they enable [FrankerZ and BetterTTV](https://github.com/chatty/chatty/blob/4813c2e386413e3615485929d0cf3d53517b8d3e/src/chatty/gui/components/settings/EmoteSettings.java) - The real deal is avaible over [here](https://github.com/chatty/chatty/blob/535b88d7302c87ba54ae4c2448a96a7d2867592d/src/chatty/util/BTTVEmotes.java).

![download](https://cloud.githubusercontent.com/assets/727123/15542286/637d5ad4-2290-11e6-82fc-79df824b34c5.png)

Maybe you could implement it, would kiss you for that ... :laughing: :heart:

**Comment by CHEF-KOCH** [comment]
My offer with donation still stands for all the work.

**Comment by GlitchCog** [comment]
I'll see what I can do. I would like to include them eventually. It is a kick in the teeth that they don't officially expose their API.

And thanks, I do appreciate the offer, but...
![nofun](https://cloud.githubusercontent.com/assets/3694723/15562161/c3978f90-22ca-11e6-8e32-5519280f8fec.png)

**Comment by GlitchCog** [comment]
BetterTTV emotes have been added to the Fontificator. They can be enabled and/or cached on the Emoji tab just like the FrankerFaceZ emotes.

The animated BTTV emotes currently just show the initial frame of the animation. If anyone is interested, there is code commented out in the LazyLoadEmoji class starting with "if (animatedGif)". Uncomment that code to enable animation. There are issues with it where transparent bits aren't refreshed unless pixels change and some emotes, like "(ditto)" run at incorrect speeds. I intend to leave the animations out until I resolve these issues.

**Comment by CHEF-KOCH** [comment]
![3232](https://cloud.githubusercontent.com/assets/727123/15779231/65e1f732-299b-11e6-8e91-d5b09d99a8a6.png)

:rocket: :rocket: :rocket: :rocket: :rocket:
